// Faculty salary dataset for Bangladeshi private universities.
//
// Source: crowd-sourced data originally compiled by Asif Saad at
// https://asif-saad.github.io/blog/salary-by-faculty/
// Transcribed from the VISIBLE table rows on that page (HTML-commented rows are
// excluded). Figures are self-reported, approximate, and for informational use only.
// See README.md for how to refresh this data.

export interface SalaryRecord {
  university: string;
  shortName: string | null;
  designation: string;
  /** City/area, normalized (e.g. "Chattogram" for both spellings). Empty if the source omits it. */
  location: string;
  /** Monthly basic pay in BDT, if reported separately. */
  basic: number | null;
  /** Monthly allowances in BDT, if reported separately. */
  allowances: number | null;
  /**
   * Total monthly salary in BDT. Midpoint used when the source gives a range.
   * null when the source's pay isn't a monthly amount (per-class / per-course /
   * per-semester) — those records show rawSalary instead and are excluded from stats.
   */
  total: number | null;
  /** The salary text as written on the source page (" | " = line break there). */
  rawSalary: string;
  /** Extra benefits / bonuses / increments text, verbatim from the source. */
  facilities: string;
  /** Month + year the entry was last updated, as written on the source. */
  lastUpdated: string;
}

export const salaries: SalaryRecord[] = [
  { university: "Ahsanullah University of Science and Technology", shortName: "AUST", designation: "Lecturer", location: "Dhaka", basic: 33000, allowances: 28000, total: 61000, rawSalary: "Basic: 33k | Others: 28k", facilities: "Increment: 7% of basic after 1st year. After 2nd year, promoted to Senior Lecturer", lastUpdated: "November 2025" },
  { university: "Ahsanullah University of Science and Technology", shortName: "AUST", designation: "Adjunct Faculty", location: "Dhaka", basic: null, allowances: null, total: null, rawSalary: "", facilities: "Max 6 credit. Per class 2300 tk(theory) 1300 tk (Sessional)", lastUpdated: "April 2025" },
  { university: "Anwer Khan Modern University", shortName: null, designation: "Lecturer", location: "Dhaka", basic: null, allowances: null, total: 40000, rawSalary: "Total: 40k", facilities: "", lastUpdated: "October 2025" },
  { university: "Asian University of Bangladesh", shortName: null, designation: "Lecturer", location: "Ashulia", basic: null, allowances: null, total: 25000, rawSalary: "Total: 25k", facilities: "Fixed two weekend holidays, Research Publication Incentives, Festival Bonus, Loan, Bus Transport.", lastUpdated: "May 2025" },
  { university: "Atish Dipankar University of Science & Technology", shortName: "ADUST", designation: "Lecturer", location: "Dhaka", basic: null, allowances: null, total: 30000, rawSalary: "Total: 30k", facilities: "Increment: 5% of total salary (once a year) | Festival Bonus: Yearly 2 times, 60% of total salary | Thesis Bill: 1k per one project student. | Committee Member: 3k", lastUpdated: "January 2024" },
  { university: "Bangladesh Army University of Engineering & Technology", shortName: "BAUET", designation: "Lecturer", location: "Natore", basic: null, allowances: null, total: 41500, rawSalary: "Total: 41k-42k", facilities: "Some other additional fees at the end of a semester", lastUpdated: "August 2024" },
  { university: "Bangladesh Army University of Science and Technology", shortName: "BAUST", designation: "Lecturer", location: "Saidpur", basic: 22000, allowances: 19000, total: 41000, rawSalary: "Basic: 22k | House Rent: 8.8k | Medical: 1.2k | Education: 1k | Phone: 1.5k | Total: 41k", facilities: "Exam Bill: 5k-10k (per semester) | Bonus: 2 times a year (Full Basic After Probation Period, 25% After 6Months, 50% After 9Months) | Increment: 5% per year, Max 8 times in job life", lastUpdated: "August 2024" },
  { university: "Bangladesh Military Academy (Extended Campus of MiST)", shortName: null, designation: "Contractual Lecturer (Full time)", location: "Chattogram", basic: null, allowances: null, total: 40000, rawSalary: "Total: 40k+ (around)", facilities: "Exam Bill: 16k-20k (per semester) | Bonus: 32k Eid bonus, 2 times a year. New Year Bonus 8k. | Increment: 4% annual increment. After 1st year, 41.6k, next increment is of 4% on 41.6k and so on.", lastUpdated: "August 2024" },
  { university: "Bangladesh University of Business and Technology", shortName: "BUBT", designation: "Lecturer", location: "Dhaka", basic: 34500, allowances: 22500, total: 57000, rawSalary: "Basic: 34.5k | House rent: 55% of basic | Medical: 2k | Conveyance: 2k | Total: 57k", facilities: "Increment: 1k | Extra Credit: per overload course = 47k (end of semester) | Exam Bill: 100-400 per exam duty | Eid Bonus: twice a year. (equivalent of basic) Baishakhi Bonus: 20% of basic", lastUpdated: "April 2025" },
  { university: "Bangladesh University of Professionals", shortName: "BUP", designation: "Lecturer (on probation)", location: "Dhaka", basic: 25000, allowances: 15500, total: 40000, rawSalary: "Basic: 25k (around) | House: 14k | Medical: 1.5k | Total: 40k (around)", facilities: "Exam bill, Administrative working bill | Deduction: GP fund, welfare fund, transport", lastUpdated: "January 2025" },
  { university: "BRAC University", shortName: null, designation: "Lecturer (Contractual)", location: "", basic: null, allowances: null, total: null, rawSalary: "Total: 234k per semester after taxes. Paid in two installments.", facilities: "", lastUpdated: "May 2024" },
  { university: "BRAC University", shortName: null, designation: "Lecturer (Permanent)", location: "", basic: null, allowances: null, total: 85500, rawSalary: "Total: 85.5k", facilities: "", lastUpdated: "January 2025" },
  { university: "Canadian University Bangladesh", shortName: null, designation: "Lecturer", location: "Dhaka", basic: null, allowances: null, total: 40000, rawSalary: "Total: 40k", facilities: "", lastUpdated: "February 2025" },
  { university: "City University", shortName: null, designation: "Lecturer", location: "Savar", basic: null, allowances: null, total: 35000, rawSalary: "Total: 35k", facilities: "Bonus: 22k, twice a year", lastUpdated: "February 2025" },
  { university: "Daffodil International University", shortName: "DIU", designation: "Lecturer", location: "Savar", basic: 23000, allowances: 27000, total: 50000, rawSalary: "Basic: 23k | House: 11.5k | Medical: 5.5k | Transport: 1.5k | Recreation: 3k | Allowance: 2.5k (on card, inside campus only) | Total: 50k", facilities: "Exam Bill: 28k | Extra Credit: 14k | Increment: 8k | Bonus: 5k", lastUpdated: "August 2024" },
  { university: "East Delta University", shortName: "EDU", designation: "Lecturer", location: "Chattogram", basic: 20000, allowances: 15000, total: 35000, rawSalary: "Basic: 20k | Others: 15k", facilities: "Extra Course: 1.1k per credit hour (39 hrs for 3 credits) | Increment: 7k | Thesis: 3k | Bonus: 100% of basic, twice a year", lastUpdated: "August 2024" },
  { university: "East West University", shortName: "EWU", designation: "Lecturer", location: "", basic: 50000, allowances: 29000, total: 79000, rawSalary: "Basic: 50k | House Rent: 25k | Medical: 4k", facilities: "", lastUpdated: "February 2025" },
  { university: "Eastern University of Bangladesh", shortName: null, designation: "Lecturer", location: "Ashulia", basic: null, allowances: null, total: 37000, rawSalary: "Total: 37k", facilities: "Increment: 5% (per year)", lastUpdated: "October 2024" },
  { university: "European University of Bangladesh", shortName: null, designation: "Lecturer", location: "Dhaka", basic: null, allowances: null, total: 37500, rawSalary: "Total: 30k-45k", facilities: "Increment: 10% (per year) | Eid Bonus: twice, 33%", lastUpdated: "October 2024" },
  { university: "EXIM Bank Agricultural University Bangladesh", shortName: null, designation: "Lecturer (Permanent)", location: "Chapainawabganj", basic: null, allowances: null, total: 35000, rawSalary: "Total: 35k", facilities: "Boishaki Bonus: 4.2k | Eid Bonus: twice, 21k each time", lastUpdated: "February 2025" },
  { university: "German University Bangladesh", shortName: null, designation: "Lecturer (Part time)", location: "Gazipur", basic: null, allowances: null, total: 25000, rawSalary: "Total: 25k", facilities: "", lastUpdated: "August 2024" },
  { university: "Green University of Bangladesh", shortName: "GUB", designation: "Lecturer", location: "Purbachal", basic: 28000, allowances: 29000, total: 56000, rawSalary: "Basic: 28k | House: 14k | Medical: 8k | Transport: 5k | NAT: 2k | Total: 55k-57k", facilities: "Exam Bill: varying (approximately 650-750) | Increment: general 5%, if have conference paper 10%, if have journal 20% | Extra credit: per course 35k (end of semester) | Thesis fee: 15*4k =60k, industrial training fee: 15*3=45k (end of each semester)", lastUpdated: "August 2024" },
  { university: "Hamdard University Bangladesh", shortName: "HUB", designation: "Lecturer (Permanent)", location: "Munshiganj", basic: null, allowances: null, total: 35000, rawSalary: "Total: 35k", facilities: "Bonus: 22k, Twice a year", lastUpdated: "August 2024" },
  { university: "International Islamic University Chittagong", shortName: "IIUC", designation: "Assistant Lecturer", location: "Chattogram", basic: 22500, allowances: 17500, total: 40000, rawSalary: "Basic: 22.5k | Total: 40k (around)", facilities: "Extra course Bill: around 500, each class | Additionally, Two times festival bonus, exam copy bill, exam hall guard bill, after semester end.", lastUpdated: "August 2024" },
  { university: "International Standard University", shortName: null, designation: "Lecturer (Permanent)", location: "Dhaka", basic: 22000, allowances: 18000, total: 40000, rawSalary: "Basic: 22k | Total: 40k", facilities: "Increment: 5% of total salary | Bonus: twice a year, basic of salary | Thesis+Internship: 3k per student | For extra credits, like 15 credits are mandatory to be taken by the lecturers and for each extra credit assigned, a lecturer gets 10,333 taka per semester per credit. So, if as a lecturer I take 18 credits in a semester, which is 3 credits extra, that will bring be a total of 32,000 taka after closing the semester.", lastUpdated: "February 2025" },
  { university: "International University of Business Agriculture and Technology", shortName: "IUBAT", designation: "Lecturer", location: "Dhaka", basic: 45000, allowances: 27000, total: 72000, rawSalary: "Basic: 45k | House Rent: 22.5k | Medical Allowance: 4.5k | Total: 72k (around)", facilities: "Bonus: full basic, 2 times a year (after 1 year probation period) | Boishakhi Allowance: 10% of basic | Increment: 10% - 20% of basic", lastUpdated: "July 2025" },
  { university: "Khulna Khan Bahadur Ahsanullah University", shortName: null, designation: "Lecturer (Permanent)", location: "Khulna", basic: 22000, allowances: 10000, total: 32000, rawSalary: "Basic: 22k | House rent: 40% of basic | Medical: 1.5k | Total: 32k (around)", facilities: "", lastUpdated: "August 2024" },
  { university: "Metropolitan University", shortName: null, designation: "Lecturer", location: "Sylhet", basic: 22000, allowances: 13900, total: 35900, rawSalary: "Basic: 22k | Total: 35.9k (around)", facilities: "Increment: 10% of basic per year | Bonus: 100% of basic, two Eid", lastUpdated: "December 2024" },
  { university: "North South University", shortName: "NSU", designation: "Lecturer", location: "Dhaka", basic: 59000, allowances: 46000, total: 105000, rawSalary: "Basic: 59k (around) | Others (House rent, medical etc.): 46k (around)", facilities: "Bonus: full basic, 2 times a year | Boishakhi Allowance: 10% of basic | Increment: 10% of basic per year | Extra course load adjusted as per regulations.", lastUpdated: "August 2024" },
  { university: "North Western University", shortName: null, designation: "Lecturer", location: "Khulna", basic: null, allowances: null, total: 32000, rawSalary: "Total: 32k (around)", facilities: "", lastUpdated: "April 2025" },
  { university: "Northern University Bangladesh", shortName: "NUB", designation: "Lecturer", location: "Dhaka", basic: null, allowances: null, total: 50000, rawSalary: "Total: 50k", facilities: "Increment: 5% | Bonus: 75% of basic, 2 times a year | Extra credit: 8k per credit (after 1 year)", lastUpdated: "April 2025" },
  { university: "Port City International University", shortName: "PCIU", designation: "Lecturer (Contractual)", location: "Chattogram", basic: null, allowances: null, total: 28000, rawSalary: "Total: 28k", facilities: "Extra credit: 12k per course", lastUpdated: "August 2025" },
  { university: "Presidency University", shortName: null, designation: "Lecturer (Full-time)", location: "Dhaka", basic: 35000, allowances: 18500, total: 53500, rawSalary: "Basic: 35k | Total: 50k-57k", facilities: "Thesis Bill: 18k/21k per 6/7 students' group", lastUpdated: "September 2024" },
  { university: "Primeasia University", shortName: null, designation: "Lecturer (Full-time)", location: "Dhaka", basic: 14000, allowances: 16000, total: 30000, rawSalary: "Basic: 14k | Total: 30k (around)", facilities: "", lastUpdated: "July 2024" },
  { university: "Prime University", shortName: null, designation: "Lecturer", location: "Dhaka", basic: null, allowances: null, total: 30000, rawSalary: "Total: 30k", facilities: "Extra Course Bill: 27k taka for 3 credit course (6 months semester) | Exam Bill: around 1k (per semester) | Increment: After 1st, 2.5k increment | Project/Thesis Bill: 5.4k, 3 students group. (1.8k, each student) | Bonus: Around 1.4k, 2 times a year", lastUpdated: "August 2024" },
  { university: "Premier University", shortName: null, designation: "Lecturer", location: "", basic: 22000, allowances: 17000, total: 39000, rawSalary: "Basic: 22k | Total: 39k", facilities: "Extra Course Bill: around 25k for 3 credit | Exam Bill: around 10k-15k (per semester) | Increment: 5% of basic | Project/Thesis Bill: 7k per group | Bonus: 22k, 2 times a year", lastUpdated: "January 2025" },
  { university: "Shanto-Mariam University of Creative Technology", shortName: "SMUCT", designation: "Lecturer", location: "Dhaka", basic: 20000, allowances: 17900, total: 37900, rawSalary: "Basic: 20k | House: 10k | Transport: 3k | Medical: 2k | Others: 2.9k", facilities: "Exam Bill: 100-200/duty (varying)", lastUpdated: "August 2024" },
  { university: "Brahmaputra International University", shortName: "BRIU", designation: "Lecturer", location: "Jamalpur", basic: 22000, allowances: 5000, total: 26000, rawSalary: "Basic: 22k | House: 1.5k | Technical Allowance: 2k | Medical: 1.5k | Total: 25k-27k", facilities: "Exam Bill: 1.1k-1.4k/duty | Exam Copy Check Bill: 1.5k | Increment: 5% of basic | Bonus: 75% of basic, twice a year(eid bonus) | Boishakhi Bonus: 10% of basic | Extra Credit Bill: 2.5k/credit", lastUpdated: "May 2025" },
  { university: "Southeast University", shortName: "SEU", designation: "Lecturer", location: "Dhaka", basic: null, allowances: null, total: 67500, rawSalary: "for 6 courses: 65k-70k", facilities: "Bonus: 100% of basic, twice a year | 1st year provisonal period, 2nd year permanent, increment after 2nd year", lastUpdated: "February 2025" },
  { university: "Southeast University", shortName: "SEU", designation: "Lecturer (Contractual)", location: "Dhaka", basic: null, allowances: null, total: null, rawSalary: "50k for 1 theory course 3 credit, 25k for each lab course, Max 6 credits are given to Contractual teachers", facilities: "", lastUpdated: "June 2025" },
  { university: "Sonargaon University", shortName: null, designation: "Lecturer (On-probation)", location: "Dhaka", basic: 20000, allowances: 14900, total: 34900, rawSalary: "Basic: 20k | House: 10k | Medical: 2k | Others: 2.9k", facilities: "Increment: 10% (basic) | Extra Credit: 20k per 3 credit", lastUpdated: "August 2024" },
  { university: "Southern University Bangladesh", shortName: null, designation: "Lecturer", location: "Chattogram", basic: null, allowances: null, total: 30000, rawSalary: "Total: 25k-35k", facilities: "Increment, Bonus, Thesis Bill, Extra Course Bill", lastUpdated: "November 2025" },
  { university: "Sylhet International University", shortName: null, designation: "Lecturer (permanent)", location: "Sylhet", basic: null, allowances: null, total: 32500, rawSalary: "Total: 30k-35k", facilities: "", lastUpdated: "February 2025" },
  { university: "Teesta University", shortName: null, designation: "Lecturer", location: "Rangpur", basic: null, allowances: null, total: 30000, rawSalary: "Total: 30K", facilities: "", lastUpdated: "August 2024" },
  { university: "United International University", shortName: "UIU", designation: "Lecturer", location: "Dhaka", basic: null, allowances: null, total: 78000, rawSalary: "Total: 2 Theory, 2 Lab - 78k (4 courses) | Overload in Trimester: Theory - 3 credit - 57750 (Per trimester) | Overload in Trimester: Lab - 1 credit - 0.7*57750 (Per trimester)", facilities: "Increment: 5k | Bonus: Full basic salary, twice a year", lastUpdated: "August 2024" },
  { university: "United International University", shortName: "UIU", designation: "Research Assistant (contractual)", location: "Dhaka", basic: null, allowances: null, total: 23000, rawSalary: "Started With 15K and later increased to 23K", facilities: "No additional facilities. But always worked from home. Never had any in-person meetings.", lastUpdated: "July 2023" },
  { university: "University of Asia Pacific", shortName: "UAP", designation: "Lecturer", location: "Dhaka", basic: 38000, allowances: 30500, total: 68500, rawSalary: "Basic: 38k | House: 23k | Medical: 5k | Conveyance: 2.5k", facilities: "", lastUpdated: "January 2025" },
  { university: "University of Information Technology & Sciences", shortName: "UITS", designation: "Lecturer", location: "Dhaka", basic: null, allowances: null, total: 40000, rawSalary: "Total: 40k", facilities: "Bonus: 6 times a year, 16k each time | Extra Credit: 20k+- | Exam duty + Exam copy check: around 10k", lastUpdated: "August 2024" },
  { university: "University of Scholars", shortName: null, designation: "Lecturer (Full Time)", location: "Dhaka", basic: null, allowances: null, total: 30000, rawSalary: "Total: 30k", facilities: "Bonus: 50% of salary", lastUpdated: "November 2025" },
  { university: "University of Science and Technology Chittagong", shortName: "USTC", designation: "Lecturer", location: "Chattogram", basic: null, allowances: null, total: 32500, rawSalary: "Total: 30k-35k", facilities: "Exam Bill: 20k - 30k (per semester) | Two festival bonus", lastUpdated: "June 2023" },
  { university: "University of Skill Enrichment and Technology", shortName: "USET", designation: "Lecturer (permanent)", location: "Narayanganj", basic: null, allowances: null, total: 25000, rawSalary: "Total: 25k", facilities: "", lastUpdated: "April 2025" },
  { university: "Uttara University", shortName: null, designation: "Lecturer", location: "Dhaka", basic: null, allowances: null, total: 45000, rawSalary: "Total: 45k", facilities: "Extra Credit: 13k | Increment: general 5% | Bonus: 30%", lastUpdated: "August 2024" },
  { university: "Varendra University", shortName: null, designation: "Lecturer (On Probation)", location: "Rajshahi", basic: null, allowances: null, total: 33500, rawSalary: "Total: 33.5k", facilities: "", lastUpdated: "April 2024" },
  { university: "World University of Bangladesh", shortName: null, designation: "Lecturer", location: "", basic: null, allowances: null, total: 32750, rawSalary: "Total: 30.5k (without M.Sc.), 35K (with M.Sc.)", facilities: "Thesis supervision fee, Yearly increment - 1st year- 1k, 2nd year- 2k", lastUpdated: "August 2025" },
];
